### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by growlithes** [Darkhax-Minecraft/BadMobs#21]
I keep getting this error:
The game crashed whilst rendering overlay
Error: com.electronwill.nightconfig.core.io.ParsingException: Invalid value: “minecraft:creeper”

Crash report:
---- Minecraft Crash Report ----
// My bad.

Time: 10/7/19 6:10 PM
Description: Rendering overlay

com.electronwill.nightconfig.core.io.ParsingException: Invalid value: “minecraft:creeper”
	at com.electronwill.nightconfig.toml.ValueParser.parseNumber(ValueParser.java:101) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:63) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.toml.ArrayParser.parse(ArrayParser.java:31) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:32) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:68) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:57) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:101) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:88) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.0.jar:?] {}
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:53) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:99) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_74] {}
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:149) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$startModLoading$6(ClientModLoader.java:105) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:95) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:105) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:87) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:95) ~[?:?] {pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_74] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_74] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.electronwill.nightconfig.toml.ValueParser.parseNumber(ValueParser.java:101)
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:63)
	at com.electronwill.nightconfig.toml.ArrayParser.parse(ArrayParser.java:31)
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:32)
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:68)
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:57)
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:101)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:88)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37)
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202)
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73)
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85)
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:53)
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:99)
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83)
	at java.lang.Iterable.forEach(Iterable.java:75)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:544)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:887)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Mac OS X (x86_64) version 10.11.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 614894768 bytes (586 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.0
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		BadMobs-1.14.4-3.0.1.jar BadMobs {badmobs@3.0.1 COMMON_SETUP}
		inventorysorter-1.14.4-16.0.0.jar Simple Inventory Sorter {inventorysorter@16.0.0 COMMON_SETUP}
		worldedit-forge-mc1.14.4-7.0.1.jar WorldEdit {worldedit@7.0.1;61bc012 COMMON_SETUP}
		Xaeros_Minimap_1.18.1.1_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@1.18.1.1 COMMON_SETUP}
		forge-1.14.4-28.1.0-universal.jar Forge {forge@28.1.0 COMMON_SETUP}
		forge-1.14.4-28.1.0-client.jar Minecraft {minecraft@1.14.4 COMMON_SETUP}
	Launched Version: 1.14.4-forge-28.1.0
	LWJGL: 3.2.1 build 12
	OpenGL: Intel HD Graphics 3000 OpenGL Engine GL version 2.1 INTEL-10.0.52, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz

**Comment by Darkhax** [comment]
You've typed your config file wrong. It needs to be ["value1", "value2"].

**Comment by growlithes** [comment]
I put it in brackets but it stills says invalid value.
